spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mb
    password: 1123
    url: jdbc:mysql://localhost:3306/wego
server:
  port: 8081
mybatis:
  configuration:
    map-underscore-to-camel-case: true
